/**
 * Netflix で配信された／されている実在の映画タイトル（オリジナル・ライセンス含む）。
 * 地域・時期により取り扱いは異なります。シード用の参考リストです。
 */
export const NETFLIX_FILM_TITLES: string[] = [
  // --- 既存シードに近い枠 + 追加（重複は seed 側で除去） ---
  'The Irishman',
  'Marriage Story',
  'Roma',
  'Bird Box',
  "Don't Look Up",
  'Red Notice',
  'Extraction',
  'The Gray Man',
  'Glass Onion: A Knives Out Mystery',
  'The Adam Project',
  'The Mother',
  'Leave the World Behind',
  'Rebel Moon — Part One: A Child of Fire',
  'Rebel Moon — Part Two: The Scargiver',
  'They Cloned Tyrone',
  'The Killer',
  'Maestro',
  'May December',
  'Players',
  'Spaceman',
  'Damsel',
  'The Old Guard',
  '6 Underground',
  'Bright',
  'Okja',
  'Beasts of No Nation',
  'The Power of the Dog',
  'Mank',
  "Ma Rainey's Black Bottom",
  'The Trial of the Chicago 7',
  'All Quiet on the Western Front',
  "Guillermo del Toro's Pinocchio",
  'The Sea Beast',
  'Wendell & Wild',
  'The Good Nurse',
  'The Wonder',
  'White Noise',
  'Blonde',
  'Pearl',
  'Luther: The Fallen Sun',
  'We Have a Ghost',
  'Your Place or Mine',
  'You People',
  'The Woman King',
  "Lady Chatterley's Lover",
  'The School for Good and Evil',
  'Slumberland',
  'The Pale Blue Eye',
  'You Are So Not Invited to My Bat Mitzvah',
  'Pain Hustlers',
  'Nyad',
  'Hit Man',
  'Irish Wish',
  'Atlas',
  'Heart of Stone',
  'Lift',
  'Spenser Confidential',
  'Hubie Halloween',
  'Eurovision Song Contest: The Story of Fire Saga',
  'The Prom',
  'Holidate',
  'Dolemite Is My Name',
  'El Camino: A Breaking Bad Movie',
  'The Ballad of Buster Scruggs',
  '1922',
  "Gerald's Game",
  'The King',
  'Outlaw King',
  'Triple Frontier',
  'Always Be My Maybe',
  'Murder Mystery',
  'Murder Mystery 2',
  'The Bubble',
  'The Out-Laws',
  'We Can Be Heroes',
  'Sweet Girl',
  'Beckett',
  'Night Teeth',
  'Blood Red Sky',
  'Kate',
  'Gunpowder Milkshake',
  'The Ice Road',
  'Thunder Force',
  'Stowaway',
  'Oxygen',
  'I Care a Lot',
  'I Came By',
  'The Royal Treatment',
  'Love and Monsters',
  'The Old Ways',
  'Fear Street Part 1: 1994',
  'Fear Street Part 2: 1978',
  'Fear Street Part 3: 1666',
  'tick, tick… BOOM!',
  'Passing',
  'The Harder They Fall',
  'Bruised',
  'Concrete Cowboy',
  'Malcolm & Marie',
  'The White Tiger',
  'The Two Popes',
  // --- 追加: Netflix オリジナル・配信映画（拡大） ---
  'The Mitchells vs. The Machines',
  'Klaus',
  'Over the Moon',
  'Back to the Outback',
  'Apollo 10½: A Space Age Childhood',
  'The Magician’s Elephant',
  'Nimona',
  'Chicken Run: Dawn of the Nugget',
  'That Christmas',
  'The Christmas Chronicles',
  'The Christmas Chronicles 2',
  'A Boy Called Christmas',
  'Jingle Jangle: A Christmas Journey',
  'The Princess Switch',
  'The Princess Switch: Switched Again',
  'The Princess Switch: Romancing the Star',
  'Falling for Christmas',
  'Let It Snow',
  'Operation Christmas Drop',
  'A Castle for Christmas',
  'Best. Christmas. Ever!',
  'Family Switch',
  'Dog Gone',
  'Rescued by Ruby',
  'Togo',
  'The Starling',
  'Fatherhood',
  'Otherhood',
  'Yes Day',
  'The Main Event',
  'Finding Ohana',
  'Mixtape',
  '13: The Musical',
  'Along for the Ride',
  'Purple Hearts',
  'Chemical Hearts',
  'All Together Now',
  'Tall Girl',
  'Tall Girl 2',
  'The Kissing Booth',
  'The Kissing Booth 2',
  'The Kissing Booth 3',
  'To All the Boys I’ve Loved Before',
  'To All the Boys: P.S. I Still Love You',
  'To All the Boys: Always and Forever',
  'The Perfect Date',
  'Sierra Burgess Is a Loser',
  'The Half of It',
  'Do Revenge',
  'Moxie',
  'Enola Holmes',
  'Enola Holmes 2',
  'Persuasion',
  'Rebecca',
  'The Dig',
  'The Guilty',
  'Windfall',
  'The Devil All the Time',
  'I’m Thinking of Ending Things',
  'His House',
  'The Platform',
  'Cargo',
  'Rim of the World',
  'The Silence',
  'Eli',
  'In the Tall Grass',
  'Fractured',
  'Wounds',
  'Rattlesnake',
  'In the Shadow of the Moon',
  'Velvet Buzzsaw',
  'Polar',
  'Hold the Dark',
  'Apostle',
  'Cam',
  'Tau',
  'How It Ends',
  'Extinction',
  'IO',
  'The Cloverfield Paradox',
  'Mute',
  'What Happened to Monday',
  'Death Note',
  'Bright',
  'Spectral',
  'ARQ',
  'iBoy',
  'Small Crimes',
  'Tramps',
  'The Most Hated Woman in America',
  'War Machine',
  'Sand Castle',
  'Burning Sands',
  'Deidra & Laney Rob a Train',
  'The Discovery',
  'Coin Heist',
  'Mercenary',
  'Crouching Tiger, Hidden Dragon: Sword of Destiny',
  'Pee-wee’s Big Holiday',
  'Special Correspondents',
  'The Do-Over',
  'The Ridiculous 6',
  'A Very Murray Christmas',
  'The Fundamentals of Caring',
  'The Siege of Jadotville',
  'Mascots',
  'True Memoirs of an International Assassin',
  'Take the 10',
  // 国際・受賞作・ライセンス枠（代表的タイトル）
  'The Social Network',
  'Inception',
  'The Dark Knight',
  'Interstellar',
  'Django Unchained',
  'Inglourious Basterds',
  'The Hateful Eight',
  'Once Upon a Time in Hollywood',
  'Knives Out',
  'Looper',
  'Snowpiercer',
  'Okja',
  'Parasite',
  'Minari',
  'The Farewell',
  'Past Lives',
  'Everything Everywhere All at Once',
  'The Banshees of Inisherin',
  'The Fabelmans',
  'Tár',
  'Women Talking',
  'The Whale',
  'Elvis',
  'Top Gun: Maverick',
  'Dune',
  'Dune: Part Two',
  'No Time to Die',
  'Glass Onion: A Knives Out Mystery',
  'The Batman',
  'Spider-Man: No Way Home',
  'Spider-Man: Into the Spider-Verse',
  'Spider-Man: Across the Spider-Verse',
  'Encanto',
  'Turning Red',
  'Lightyear',
  'Soul',
  'Luca',
  'Onward',
  'Toy Story 4',
  'Frozen II',
  'Moana',
  'Zootopia',
  'Big Hero 6',
  'Coco',
  'Finding Dory',
  'Inside Out',
  'The Incredibles 2',
  'Ratatouille',
  'WALL-E',
  'Up',
  'Cars 3',
  'Avengers: Endgame',
  'Avengers: Infinity War',
  'Black Panther',
  'Black Panther: Wakanda Forever',
  'Doctor Strange in the Multiverse of Madness',
  'Thor: Love and Thunder',
  'Shang-Chi and the Legend of the Ten Rings',
  'Eternals',
  'Captain Marvel',
  'Ant-Man and the Wasp: Quantumania',
  'Guardians of the Galaxy Vol. 3',
  'Deadpool',
  'Deadpool 2',
  'Logan',
  'X-Men: Days of Future Past',
  'The Matrix',
  'The Matrix Reloaded',
  'The Matrix Revolutions',
  'The Matrix Resurrections',
  'John Wick',
  'John Wick: Chapter 2',
  'John Wick: Chapter 3 – Parabellum',
  'John Wick: Chapter 4',
  'Mad Max: Fury Road',
  'Fury',
  'Baby Driver',
  'Drive',
  'Nightcrawler',
  'Prisoners',
  'Arrival',
  'Sicario',
  'Blade Runner 2049',
  'Dune',
  'The Martian',
  'Gravity',
  'Interstellar',
  'Ad Astra',
  'First Man',
  'Oppenheimer',
  'Tenet',
  'Dunkirk',
  'The Dark Knight Rises',
  'Batman Begins',
  'Joker',
  'The Batman',
  'Birds of Prey',
  'Suicide Squad',
  'The Suicide Squad',
  'Wonder Woman',
  'Wonder Woman 1984',
  'Aquaman',
  'Shazam!',
  'Black Adam',
  'Fast & Furious',
  'Fast Five',
  'Furious 7',
  'The Fate of the Furious',
  'F9',
  'Fast X',
  'Hobbs & Shaw',
  'Mission: Impossible – Fallout',
  'Mission: Impossible – Dead Reckoning Part One',
  'Top Gun',
  'Creed',
  'Creed II',
  'Creed III',
  'Rocky',
  'The Equalizer',
  'The Equalizer 2',
  'The Equalizer 3',
  'Taken',
  'Taken 2',
  'Taken 3',
  'The Transporter',
  'Crank',
  'The Expendables',
  'The Expendables 2',
  'The Expendables 3',
  'Rambo: Last Blood',
  'Terminator 2: Judgment Day',
  'Terminator: Dark Fate',
  'Alien',
  'Aliens',
  'Prometheus',
  'Alien: Covenant',
  'Predator',
  'Prey',
  'The Terminator',
  'Total Recall',
  'Minority Report',
  'War of the Worlds',
  'Ready Player One',
  'Pacific Rim',
  'Godzilla',
  'Kong: Skull Island',
  'Godzilla vs. Kong',
  'King Kong',
  'Jurassic World',
  'Jurassic World: Fallen Kingdom',
  'Jurassic World Dominion',
  'Jaws',
  'E.T. the Extra-Terrestrial',
  'Close Encounters of the Third Kind',
  'Indiana Jones and the Raiders of the Lost Ark',
  'Indiana Jones and the Temple of Doom',
  'Indiana Jones and the Last Crusade',
  'Indiana Jones and the Kingdom of the Crystal Skull',
  'Indiana Jones and the Dial of Destiny',
  'Back to the Future',
  'Back to the Future Part II',
  'Back to the Future Part III',
  'Ghostbusters',
  'Ghostbusters: Afterlife',
  'Men in Black',
  'Independence Day',
  'The Day After Tomorrow',
  '2012',
  'San Andreas',
  'Skyscraper',
  'Rampage',
  'Jumanji: Welcome to the Jungle',
  'Jumanji: The Next Level',
  'Pirates of the Caribbean: The Curse of the Black Pearl',
  'Pirates of the Caribbean: Dead Man’s Chest',
  'The Lord of the Rings: The Fellowship of the Ring',
  'The Lord of the Rings: The Two Towers',
  'The Lord of the Rings: The Return of the King',
  'The Hobbit: An Unexpected Journey',
  'The Hobbit: The Desolation of Smaug',
  'The Hobbit: The Battle of the Five Armies',
  'Harry Potter and the Sorcerer’s Stone',
  'Harry Potter and the Chamber of Secrets',
  'Harry Potter and the Prisoner of Azkaban',
  'Harry Potter and the Goblet of Fire',
  'Harry Potter and the Order of the Phoenix',
  'Harry Potter and the Half-Blood Prince',
  'Harry Potter and the Deathly Hallows – Part 1',
  'Harry Potter and the Deathly Hallows – Part 2',
  'Fantastic Beasts and Where to Find Them',
  'Fantastic Beasts: The Crimes of Grindelwald',
  'The Hunger Games',
  'The Hunger Games: Catching Fire',
  'The Hunger Games: Mockingjay – Part 1',
  'The Hunger Games: Mockingjay – Part 2',
  'The Ballad of Songbirds and Snakes',
  'Twilight',
  'The Twilight Saga: New Moon',
  'The Twilight Saga: Eclipse',
  'The Twilight Saga: Breaking Dawn – Part 1',
  'The Twilight Saga: Breaking Dawn – Part 2',
  'The Maze Runner',
  'Maze Runner: The Scorch Trials',
  'Maze Runner: The Death Cure',
  'Divergent',
  'The Fault in Our Stars',
  'The Notebook',
  'A Walk to Remember',
  'La La Land',
  'The Greatest Showman',
  'Bohemian Rhapsody',
  'Rocketman',
  'Elvis',
  'A Star Is Born',
  'Whiplash',
  'Soul',
  'Coco',
  'Sing',
  'Sing 2',
  'Trolls',
  'Trolls World Tour',
  'The Lego Movie',
  'The Lego Batman Movie',
  'How to Train Your Dragon',
  'How to Train Your Dragon 2',
  'Kung Fu Panda',
  'Kung Fu Panda 2',
  'Kung Fu Panda 3',
  'Shrek',
  'Shrek 2',
  'Madagascar',
  'Despicable Me',
  'Despicable Me 2',
  'Minions',
  'Minions: The Rise of Gru',
  'The Secret Life of Pets',
  'Sing Street',
  'Yesterday',
  'Blinded by the Light',
  'CODA',
  'Sound of Metal',
  'The Sound of Music',
  'Les Misérables',
  'Chicago',
  'West Side Story',
  'In the Heights',
  'Hamilton',
  'Mamma Mia!',
  'Mamma Mia! Here We Go Again',
  'Hairspray',
  'Rock of Ages',
  'Pitch Perfect',
  'Pitch Perfect 2',
  'Pitch Perfect 3',
  'Mean Girls',
  'Clueless',
  '10 Things I Hate About You',
  'Easy A',
  'Booksmart',
  'Lady Bird',
  'Little Women',
  'Emma.',
  'Pride & Prejudice',
  'Atonement',
  'The Theory of Everything',
  'The Imitation Game',
  'The King’s Speech',
  'Darkest Hour',
  '1917',
  'Dunkirk',
  'Hacksaw Ridge',
  'Fury',
  'American Sniper',
  'Zero Dark Thirty',
  'Argo',
  'Lincoln',
  'Schindler’s List',
  'Saving Private Ryan',
  'Catch Me If You Can',
  'The Terminal',
  'Bridge of Spies',
  'The Post',
  'The Irishman',
  'The Wolf of Wall Street',
  'The Departed',
  'Goodfellas',
  'Casino',
  'Heat',
  'Collateral',
  'The Aviator',
  'Gangs of New York',
  'Shutter Island',
  'The Revenant',
  'The Great Gatsby',
  'Babylon',
  'Once Upon a Time in Hollywood',
  'Django Unchained',
  'Kill Bill: Vol. 1',
  'Kill Bill: Vol. 2',
  'Pulp Fiction',
  'Reservoir Dogs',
  'Jackie Brown',
  'From Dusk Till Dawn',
  'Sin City',
  'Planet Terror',
  'Death Proof',
  'Inglourious Basterds',
  'The Hateful Eight',
  'The 8th Night',
  'Okja',
  'Snowpiercer',
  'Parasite',
  'Train to Busan',
  'Oldboy',
  'The Host',
  'Burning',
  'Decision to Leave',
  'Broker',
  'Shoplifters',
  'Drive My Car',
  'Wheel of Fortune and Fantasy',
  'RRR',
  'Baahubali: The Beginning',
  'Baahubali 2: The Conclusion',
  'Dangal',
  'Lagaan',
  'Slumdog Millionaire',
  'Life of Pi',
  'The Lunchbox',
  'Gangs of Wasseypur',
  'Tumbbad',
  'Andhadhun',
  'Drishyam',
  'KGF: Chapter 1',
  'KGF: Chapter 2',
  'The White Tiger',
  'Lion',
  'Hotel Mumbai',
  'The Man Who Knew Infinity',
  'The Two Popes',
  'Roma',
  'Y Tu Mamá También',
  'Pan’s Labyrinth',
  'The Platform',
  'Veronica',
  'The Invisible Guest',
  'Mirage',
  'The Body',
  'Money Heist: The Phenomenon',
  'Through My Window',
  '365 Days',
  '365 Days: This Day',
  'The Next 365 Days',
  'Below Zero',
  'The Paramedic',
  // 日本映画（Netflix で配信されたことのある作品の例）
  '今度は愛妻家の番だ',
  '浅田家！',
  '花束みたいな恋をした',
  '余命10年',
  '君の名は。',
  '天気の子',
  'すずめの戸締まり',
  'SPY×FAMILY CODE: White',
  'THE FIRST SLAM DUNK',
  'シン・ウルトラマン',
  'シン・ゴジラ',
  'キングダム',
  'るろうに剣心',
  'バブル',
  'BLUE GIANT',
  // --- 追加（ドキュメンタリー・オリジナル等、映画中心） ---
  'The Wonderful Story of Henry Sugar',
  'The Rat Catcher',
  'Poison',
  'The Swan',
  'Army of the Dead',
  'Army of Thieves',
  'Day Shift',
  'Orion and the Dark',
  'Leo',
  'You Are What You Eat: A Twin Experiment',
  'The Deepest Breath',
  'The Tinder Swindler',
  'Our Father',
  'The Volcano: Rescue from Whakaari',
  'Sr.',
  'Pamela: A Love Story',
  'JEEN-YUHS: A Kanye Trilogy',
  'Miss Americana',
  'Home Team',
  'Hustle',
  'Boogie',
  'Amateur',
  'Reptile',
  'Fair Play',
  'Carry-On',
  'Rebel Ridge',
  'Trigger Warning',
  'The Shadow Strays',
  'The Electric State',
  'Frankenstein',
  'Spaceman',
  'The Killer',
]

